$init_script = <<SCRIPT
echo hello world work
date
SCRIPT

Vagrant.configure("2") do |config|
    config.vm.provision "shell", inline: $init_script
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = "1024"
    end
    config.vm.define "s0" do |s0|
        s0.vm.box = "centos/7"
        s0.vm.hostname = "s0.vv10"
#        s0.vm.network "public_network"
        s0.vm.network "private_network", ip: "192.168.1.1/24", virtualbox__intnet: "intnet1"
        s0.vm.network "private_network", ip: "192.168.2.1/25", virtualbox__intnet: "intnet2"
#        s0.vm.provider "virtualbox" do |vb|
#            vb.gui = true
#            vb.memory = "1024"
#        end
    end

    config.vm.define "s1" do |s1|
        s1.vm.box = "centos/7"
        s1.vm.hostname = "s1.vv10"
        s1.vm.network "private_network", ip: "192.168.1.100/24", virtualbox__intnet: "intnet1"
#        s1.vm.network "public_network", auto_config: false
    end

    config.vm.define "s2" do |s2|
        s2.vm.box = "centos/7"
        s2.vm.hostname = "s2.vv10"
        s2.vm.network "private_network", ip: "192.168.2.200/24", virtualbox__intnet: "intnet2"
#        s2.vm.network "public_network", auto_config: false
    end

end