# -*- mode: ruby -*-
# vi: set ft=ruby :

lab = {
  "vm1" => { :dns => "ansible1.vv10.eu" , :ip => "192.168.4.201", :cpus => 1, :mem => 1024, :script => "bootstrap.sh" },
}

Vagrant.configure(2) do |config|
    lab.each_with_index do |(lab_node, info), index|
        config.vm.define lab_node do |cfg|
            cfg.vm.provider :libvirt do |libvirt, override|
                cfg.vm.box = "centos/7"
                #cfg.vm.hostname "#{info[:dns]}"
                #https://www.vagrantup.com/docs/synced-folders/nfs.html
                cfg.vm.provision :shell, :path => "#{info[:script]}"
                override.vm.network "private_network", ip: "#{info[:ip]}" #  :mode => 'bridge'
                override.vm.hostname =  "#{info[:dns]}"

                cfg.vm.synced_folder "~/vagrant_share", "/vagrant_share", type: "nfs"

                libvirt.memory = "#{info[:mem]}"
                libvirt.cpus = "#{info[:cpus]}"

            end # provider
        end # define cfg
    end # lab

end
