key = File.read(File.expand_path("~/.ssh/id_rsa.pub"))

Vagrant.configure("2") do |config|

   config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", "1536"]
   end

  config.vm.define "vv10" do |vv10|
    vv10.vm.box = "centos/7"
    vv10.vm.hostname = "centos7"
    
    vv10.vm.provision "shell" do |s|
        s.path = "setup.sh"
        s.args = [key]
    end

    vv10.vm.network "private_network", ip: "192.168.50.6"
    #vv10.vm.network "forwarded_port", guest: 5432, host: 5436


  end

end
