- name: Add http rule to firewall
  become: yes
  shell: |
        firewall-cmd --get-active-zones
        firewall-cmd --zone=public --add-port={{ HTTPD_PORT }}/tcp --add-port={{ HTTPDS_PORT }}/tcp --permanent
        firewall-cmd --reload
        exit 0
  args:
    executable: /bin/bash

- name: Allow http forward calls to Cognos
  become: yes
  shell: |
        /usr/sbin/setsebool -P httpd_can_network_connect 1
        exit 0
  args:
    executable: /bin/bash